spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.101:3306/edu_ad?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Root@2024
# Redis + Klock
klock:
  redisson:
    single-server:
      address: "redis://127.0.0.1:6379"
      database: 0
      # password: yourPass
    
    